#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install nginx
sudo rm /etc/nginx/sites-enabled/default
sudo cp ./deploy/engine /etc/nginx/sites-available
sudo ln -s /etc/nginx/sites-available/engine /etc/nginx/sites-enabled/engine
sudo service nginx restart
sudo echo "configged nginx"
